exports.version = '0.0.1';

var sys = require('sys'),
  events = require('events'),
  fs = require('fs'),
  querystring = require('querystring');

var staticLogin = fs.readFileSync(__dirname + '/../static/login.html');

var SecurityProvider = function() {

  events.EventEmitter.call(this);

  var logPrefix = 'Komainu';
  var matchers = {};
  var ignoredPaths = [new RegExp('favicon.ico'), new RegExp('stylesheets/style.css')];
  var self = this;

  this.define = function(eventName, matchFunction) {
    matchers[eventName] = matchFunction;
    sys.log(logPrefix + ': implicitEventDefined (' + eventName + ')');
    self.emit('implicitEventDefined', eventName, matchFunction);
  };

  this.secure = function() {
    return function(req, res, next) {
      if (self.ignore(req.url)) {
        sys.log(logPrefix + ': Ignoring ' + req.url);
        return next();
      } else {
        sys.log(logPrefix + ': match (' + req.method + ' ' + req.url+ ')'); 
        self.emit('match', req, res, function() { 
          sys.log(logPrefix + ': Finalizing');
          next();
        });
      }
      
    };
  };

  this.ignore = function(path) {
    for (var i = 0; i < ignoredPaths.length; i++) {
      if (ignoredPaths[i].test(path))
        return true;
    }
    return false;
  };

  // Default implicit event definitions

  this.define('loginShow', function(req, res) {
    return (req.method == 'GET' && req.url == '/login');
  });

  this.define('loginRequest', function(req, res) {
    return (req.method == 'POST' && req.url == '/login');
  });

  // TODO: need to ensure the ignore() function is considered here
  this.define('authenticate', function(req, res) {
    return !/^\/login$|^\/logout$/.test(req.url);
  });

  this.define('logout', function(req, res) {
    return (req.method == 'GET' && /\/logout$/.test(req.url));
  });

  // Preconfigured event listeners

  var match = function(req, res, fin) {
    for (var key in matchers) {
      var fn = matchers[key];
      if (fn(req, res)) {
        sys.log(logPrefix + ': ' + key);
        self.emit(key, req, res, fin);
      }
    }
  };
  match.komainu = true;
  this.on('match', match);

  var loginShow = function(req, res, fin, err) {
    sys.log(logPrefix + ': Rendering login page');
    res.render('login', {title: 'Autogenerated Komainu Login Form'});
    // res.writeHead(200, {'Content-Type':'text/html'});
    // res.end(staticLogin);
  };
  loginShow.komainu = true;
  this.on('loginShow', loginShow);

  var loginRequest = function(req, res, fin) {
    req.on('data', function(data) {
      var credentials = querystring.parse(data.toString());
      sys.log(logPrefix + ': login (' + credentials.username + ')');
      self.emit('login', req, res, fin, credentials.username, credentials.password, ['LOGGED_IN_USER']);
    });
  };
  loginRequest.komainu = true;
  this.on('loginRequest', loginRequest);

  var login = function(req, res, fin, username, password, keys) {
    if (username == 'bcarr' && password == 'bcarr') {
      sys.log(logPrefix + ': initSession (' + username + ')');
      self.emit('initSession', req, res, fin, username, keys);
      sys.log(logPrefix + ': loginSuccess (' + username + ')');
      self.emit('loginSuccess', req, res, fin, username);
    } else {
      sys.log(logPrefix + ': loginFailure (' + username + ')');
      self.emit('loginFailure', req, res, fin, username);
    }
  };
  login.komainu = true;
  this.on('login', login);

  var loginSuccess = function(req, res, fin, username) {
    res.redirect('/');

    // res.writeHead(302, {'Location':'/'});
    // res.end();
  };
  loginSuccess.komainu = true;
  this.on('loginSuccess', loginSuccess);

  var loginFailure = function(req, res, fin, username) {
    sys.log(logPrefix + ': loginShow');
    self.emit('loginShow', req, res, ['Invalid Credentials']);
  };
  loginFailure.komainu = true;
  this.on('loginFailure', loginFailure);

  var logout = function(req, res, fin, username) {
   // if (!req.session.komainu)
     // throw Error('Cannot logout from a non-existent session.');

    delete req.session.komainu;

    sys.log(logPrefix + ': sessionEnded');
    self.emit('sessionEnded', req, res, fin);

    sys.log(logPrefix + ': logoutSuccess');
    self.emit('logoutSuccess', req, res, fin);
  };
  logout.komainu = true;
  this.on('logout', logout);

  var initSession = function(req, res, fin, username, keys) {
    req.session.komainu = {
      keys: keys
    }
    sys.log(logPrefix + ': sessionStarted (' + username + ' ' + keys + ')');
    self.emit('sessionStarted', req, res, fin, username, keys);
  };
  initSession.komainu = true;
  this.on('initSession', initSession);

  var logoutSuccess = function(req, res, fin) {
    res.redirect('/');
    // res.writeHead(302, {'Location':'/'});
    // res.end();
  };
  logoutSuccess.komainu = true;
  this.on('logoutSuccess', logoutSuccess);

  var authenticate = function(req, res, fin) {

    console.log(req.session);

    if (!req.session || !req.session.komainu || !req.session.komainu.keys ||
        !req.session.komainu.keys[0] === 'LOGGED_IN_USER') {

      sys.log(logPrefix + ': accessDenied');
      self.emit('accessDenied', req, res, fin);
    } else {
      sys.log(logPrefix + ': accessGranted');
      self.emit('accessGranted', req, res, fin);
    }
  };
  authenticate.komainu = true;
  this.on('authenticate', authenticate);

  var accessDenied = function(req, res, fin) {
    sys.log(logPrefix + ': loginShow');
    self.emit('loginShow', req, res, ['Access Denied']);
  };
  accessDenied.komainu = true;
  this.on('accessDenied', accessDenied);

  var accessGranted = function(req, res, fin) {
    fin();
  };
  accessGranted.komainu = true;
  this.on('accessGranted', accessGranted);

  this.on('newListener', function(event, listener) {
    var listeners = self.listeners(event);
    for (var i = 0; i < listeners.length; i++) {
      if (listeners[i].komainu) {
        sys.log(logPrefix + ': Overriding ' + event);
        self.removeListener(event, listeners[i]);
      }
    }
  });

};

sys.inherits(SecurityProvider, events.EventEmitter);

exports.SecurityProvider = SecurityProvider;
